Models/Caminhao.cs
using System.ComponentModel.DataAnnotations;

namespace CadsatroCaminhoes.Models
{
	public class Caminhao
	{
		[Key]
		public int Id { get; set; }
		
		[Required]
		public string Nome { get; set; }

		[Required]
		public string Modelo { get; set; }

		[Required]
		public int AnoFabricacao { get; set; }

		[Required]
		public int AnoModelo { get; set; }
	}
}

Models/ErrorViewModel.cs
namespace CadsatroCaminhoes.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Controllers/CaminhaoController.cs
using CadsatroCaminhoes.Data;
using CadsatroCaminhoes.Models;
using Microsoft.AspNetCore.Mvc;

namespace CadsatroCaminhoes.Controllers
{
	public class CaminhaoController : Controller
	{
		private readonly ApplicationDbContext _db;

		public CaminhaoController(ApplicationDbContext db)
		{
			_db = db;
		}

		public IActionResult Index()
		{
			IEnumerable<Caminhao> objCaminhaoList = _db.Caminhoes.ToList();
			return View(objCaminhaoList);
		}

		//GET
		public IActionResult Inserir()
		{
			return View();
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Inserir(Caminhao obj)
		{
			if (ModelState.IsValid)
			{
				_db.Caminhoes.Add(obj);
				_db.SaveChanges();
				TempData["sucess"] = "Caminhão inserido com sucesso!";
				return RedirectToAction("Index");
			}
			return View(obj);
		}

		//GET
		public IActionResult Editar(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var caminhaoFromDb = _db.Caminhoes.Find(id);

			if (caminhaoFromDb == null)
			{
				return NotFound();
			}

			return View(caminhaoFromDb);
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Editar(Caminhao obj)
		{
			if (ModelState.IsValid)
			{
				_db.Caminhoes.Update(obj);
				_db.SaveChanges();
				TempData["sucess"] = "Caminhão editado com sucesso!";
				return RedirectToAction("Index");
			}
			return View(obj);
		}

		//GET
		public IActionResult Deletar(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var caminhaoFromDb = _db.Caminhoes.Find(id);

			if (caminhaoFromDb == null)
			{
				return NotFound();
			}

			return View(caminhaoFromDb);
		}

		//POST
		[HttpPost,ActionName("Deletar")]
		[ValidateAntiForgeryToken]
		public IActionResult DeletarPOST(int? id)
		{
			var obj = _db.Caminhoes.Find(id);

			if (obj==null)
			{
				return NotFound();
			}

			_db.Caminhoes.Remove(obj);
			_db.SaveChanges();
			TempData["sucess"] = "Caminhão excluído com sucesso!";
			return RedirectToAction("Index");
		}
	}
}

Controllers/HomeController.cs
using CadsatroCaminhoes.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CadsatroCaminhoes.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Views/Caminhao/Deletar.cshtml
@model Caminhao

<form method="post" asp-action="Deletar">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary text-light">Deletar</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="Nome"></label>
			<input asp-for="Nome" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="Modelo"></label>
			<select asp-for="Modelo" disabled class="form-control">
				<option value="FH">FH</option>
				<option value="FM">FM</option>
			</select>
		</div>
		<div class="mb-3">
			<label asp-for="AnoFabricacao"></label>
			<input asp-for="AnoFabricacao" class="form-control" value="@DateTime.Now.Year" disabled/>
		</div>
		<div class="mb-3">
			<label asp-for="AnoModelo"></label>
			<select asp-for="AnoModelo" disabled class="form-control">
				<option value="@DateTime.Now.Year">@DateTime.Now.Year</option>
				<option value="@DateTime.Now.AddYears(1).Year">@DateTime.Now.AddYears(1).Year</option>
			</select>
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Deletar</button>
		<a asp-controller="Caminhao" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Voltar
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

Views/Caminhao/Editar.cshtml
@model Caminhao

<form method="post" asp-action="Editar">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary text-light">Editar</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="Nome"></label>
			<input asp-for="Nome" class="form-control" />
			<span asp-validation-for="Nome" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Modelo"></label>
			<select asp-for="Modelo" class="form-control">
				<option value="FH">FH</option>
				<option value="FM">FM</option>
			</select>
			<span asp-validation-for="Modelo" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AnoFabricacao"></label>
			<input asp-for="AnoFabricacao" class="form-control" value="@DateTime.Now.Year" disabled/>
			<span asp-validation-for="AnoFabricacao" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AnoModelo"></label>
			<select asp-for="AnoModelo" class="form-control">
				<option value="@DateTime.Now.Year">@DateTime.Now.Year</option>
				<option value="@DateTime.Now.AddYears(1).Year">@DateTime.Now.AddYears(1).Year</option>
			</select>
			<span asp-validation-for="AnoModelo" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Salvar</button>
		<a asp-controller="Caminhao" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Voltar
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

Views/Caminhao/Index.cshtml
@model IEnumerable<Caminhao>
@{
    ViewData["Title"] = "Index";
}

@if (TempData["sucess"] != null)
{
    <h2>@TempData["sucess"]</h2>
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary text-light">Lista de Caminhões</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Caminhao" asp-action="Inserir" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Inserir Novo Caminhão
            </a>
        </div>
    </div>
    <br /><br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Nome
            </th>
            <th>
                Modelo
            </th>
            <th>
                Ano de Fabricação
            </th>
            <th>
                Ano Modelo
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width:"25%">
                    @obj.Nome
                </td>
                <td width:"25%">
                    @obj.Modelo
                </td>
                <td width:"25%">
                    @obj.AnoFabricacao
                </td>
                <td width:"25%">
                    @obj.AnoModelo
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Caminhao" asp-action="Editar" asp-route-id="@obj.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Editar</a>
                        <a asp-controller="Caminhao" asp-action="Deletar" asp-route-id="@obj.Id" class="btn btn-danger mx-2"><i class="bi bi-trash"></i>Deletar</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

Views/Caminhao/Inserir.cshtml
@model Caminhao

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary text-light">Inserir Caminhão</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="Nome"></label>
			<input asp-for="Nome" class="form-control" />
			<span asp-validation-for="Nome" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Modelo"></label>
			<select asp-for="Modelo" class="form-control">
				<option value="FH">FH</option>
				<option value="FM">FM</option>
			</select>
			<span asp-validation-for="Modelo" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AnoFabricacao"></label>
			<input asp-for="AnoFabricacao" class="form-control" value="@DateTime.Now.Year" disabled/>
			<span asp-validation-for="AnoFabricacao" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AnoModelo"></label>
			<select asp-for="AnoModelo" class="form-control">
				<option value="@DateTime.Now.Year">@DateTime.Now.Year</option>
				<option value="@DateTime.Now.AddYears(1).Year">@DateTime.Now.AddYears(1).Year</option>
			</select>
			<span asp-validation-for="AnoModelo" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Inserir</button>
		<a asp-controller="Caminhao" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Voltar
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Cadastro de Caminhões</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadsatroCaminhoes</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadsatroCaminhoes.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Caminhao" asp-action="Index">Caminhão</a>
        </li>
        @*<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - Cadsatro de Caminhoes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>